### ISSUE TITLE
A100 OOM issue

### ISSUE THREAD

**Issue by ChocolateBiscuit** [amir90/MagicClay#2]
Hi, thanks for the great work and the code release. I've tried to run the demo code, as well as run MagicClay with my own meshes, but in every run, I run out of memory at what seems to be epoch 300 of the SDS optimization. Specifically, I get a torch OOM error at the backwards pass here: https://github.com/amirbarda/MagicClay/blob/main/threestudio-magicclay/system/magicclay.py#L263

Your paper says that all experiments were run with a A100-40GB GPU, which is the same as what I'm using, so I'm not sure what could be the issue here.

**Comment by amirbarda** [comment]
Apologies, I have since gotten access A100-80GB, which were used for the code cleanup and the demo configs.
you are correct, I did not notice that the demo configs do exceed the 40GB limit, and require ~ 56GB of VRAM.

for the A100-40GB configuration, you can change the batch size from 4 to 2 (in both implicit and explicit representation camera data, see screenshot)
![image](https://github.com/user-attachments/assets/156e34ae-7e4e-4c86-b537-dd30f899fc97),
which reduces the memory requirement to less than 30GB:
![image](https://github.com/user-attachments/assets/c4854cad-1fcd-48a2-a8a4-fe00970f042c)
